from typing import Dict, List

from pydantic import BaseModel, Field

from story_writer.schemas import Character, Event


class SubEvent(BaseModel):
    """
    Represents a detailed, fine-grained narrative unit decomposed from a high-level Event.
    """

    sub_event_id: str = Field(
        ...,
        description='Unique identifier for the sub-event.',
        examples=['E1_S1'],
    )
    parent_event_id: str = Field(
        ...,
        description='The ID of the parent event this sub-event belongs to.',
        examples=['E1'],
    )
    title: str = Field(..., description='A brief, descriptive title for the sub-event.')
    summary: str = Field(
        ...,
        description='A detailed description of what happens in this sub-event, forming a piece of the narrative.',
    )
    characters: List[Character] = Field(..., description='Characters involved in the sub-event')


class Chapter(BaseModel):
    """
    Represents a single chapter in the story, containing a sequence of sub-events.
    """

    chapter_id: int = Field(
        ...,
        description='The sequential number of the chapter, e.g., 1, 2, 3.',
        examples=[1],
    )
    title: str = Field(..., description='An engaging title for the chapter.')
    summary: str = Field(
        ...,
        description="A brief overview of the chapter's content, theme, or narrative focus.",
    )
    sub_event_ids: List[str] = Field(
        ...,
        description="An ordered list of sub_event_ids that constitute this chapter's narrative flow.",
    )


class StoryPlan(BaseModel):
    """
    The final output of the Planning Agents.
    This comprehensive plan contains the full event decomposition and chapter structure,
    ready to be passed to the Writing Agents.
    """

    event_graph: Dict[str, Event] = Field(..., description='The original event graph generated by the Outline Agents.')
    sub_events: Dict[str, SubEvent] = Field(
        ...,
        description='A dictionary mapping all generated sub-event IDs to their objects.',
    )
    chapters: List[Chapter] = Field(
        ...,
        description="The final, ordered list of chapters that forms the story's narrative structure.",
    )
